# Generated by Django 2.2.2 on 2019-06-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bea_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
